### ISSUE TITLE
How to use

### ISSUE THREAD

**Issue by Homer99** [tomzx/imdb-importer#4]
Hi! I'm not sure how to use this code to import my ratings? I'm new to the site and coding.

**Comment by tomzx** [comment]
Please see the README section titled [How to use](https://github.com/tomzx/imdb-importer#how-to-use).

Feel free to let me know what issue you are having if this README isn't clear enough.

**Comment by Homer99** [comment]
I don't know where to paste the code?

**Comment by Homer99** [comment]
Are you there?

**Comment by tomzx** [comment]
Sorry, I don't think I can help you with that.

This is a [PHP](http://php.net/) library, thus you need how to program in PHP. If you don't, then I suggest you learn about it and come back when you do.
