### ISSUE TITLE
Can't find autoload.php

### ISSUE THREAD

**Issue by FerdinandoLM** [tomzx/imdb-importer#5]
I'm getting an error, Fatal error: require_once() [function.require]: Failed opening required 'vendor/autoload.php' (include_path='.:') in

Due to the fact that i'm newbie in php and i'm using easyphp, how can i install autoload.php? (am I assuming right this is part of Composer?)

Thanks for the support

**Comment by tomzx** [comment]
You have to be familiar with Composer, which you can get at https://getcomposer.org/. Once you have downloaded the `composer.phar` file, in the `imdb-importer` directory, you want to run `php composer.phar install` on the command line, which will fetch this package dependencies and at the same time create the `vendor` and `vendor/autoload.php` file. If you do not have `php` available when you run this command on the command line, then you have to learn how to do that for your specific operating system.

Hope that helps.
