### ISSUE TITLE
Argument 1 passed to ImdbImporter\Importer::submit() must be of the type array, null given

### ISSUE THREAD

**Issue by FerdinandoLM** [tomzx/imdb-importer#6]
Hi, i'm getting this error and i'm unable to fix this no matter the changes i tried on the json file.

Can you please help me? 

`Catchable fatal error: Argument 1 passed to ImdbImporter\Importer::submit() must be of the type array, null given, called in C:\Program Files (x86)\EasyPHP-Devserver-16.1\eds-www\index.php on line 16 and defined in C:\Program Files (x86)\EasyPHP-Devserver-16.1\eds-www\src\ImdbImporter\Importer.php on line 56`

Given that the file .json is in the same folder of the files that calls submit(), calling it index.php which is: 

```
<?php
require_once 'vendor/autoload.php';

use ImdbImporter\Importer;

// Change FILE to the location of your input json data file
$input = json_decode(file_get_contents('list.json'));
// Another option
// $input = [['title' => 'The Mask', 'rating' => '5.0']];
// Change ID_FROM_COOKIE
$id = 'BCYq_RANDOMSTUFF_00000%0D%0A';
// Change RATING_BASE
$rating_base = '10';

$importer = new Importer($id, $rating_base);
$importer->submit($input);
```

and given the syntax of the "json" file, following the readme, which is: 

```
<?php
[
  [
    "title" => "Movie 1",
    "rating" => "4.0"
  ],
  [
    "title" => "Movie 2",
    "rating" => "10.0"
  ],
  [
    "title" => "Movie 3",
    "rating" => "5.0"
  ]
]
```

**Comment by tomzx** [comment]
Hello @FerdinandoLM,

I've updated the `README.md` in regard to your comment. It should be clearer how things are supposed to be used.

Specifically, you'll want to replace 

```php
$input = json_decode(file_get_contents('list.json'));
```

with

```php
$input = require_once 'movies.php';
```

where movies.php is the file containing your movie list.

movies.php
```php
<?php
return [
  [
    "title" => "Movie 1",
    "rating" => "4.0"
  ],
  [
    "title" => "Movie 2",
    "rating" => "10.0"
  ],
  [
    "title" => "Movie 3",
    "rating" => "5.0"
  ]
];
````

Notice I added the `return` at the beginning and the `;` at the end.

Please reread the updated `README.md` and let me know if it has cleared any confusion.

**Comment by FerdinandoLM** [comment]
thanks, worked awesomely
